title: Harshal Zalke
logo: /assets/img/pic_hz.png
description: >-
PhD Candidate 
Department of Politics
Princeton University
email: hzalke@princeton.edu
show_downloads: false
google_analytics:
theme: minima
plugins:
  - jekyll-feed
